export const generateShots = (count, percentage) => {
  const shots = [];
  for (let i = 0; i < count; i++) {
    shots.push({
      id: i + 1,
      x: Math.floor(Math.random() * 80) + 10,
      y: Math.floor(Math.random() * 80) + 10,
      made: Math.random() * 100 < percentage,
      shotType: Math.random() > 0.5 ? 'TWO_POINT' : 'THREE_POINT',
    });
  }
  return shots;
};

export const DEMO_PLAYERS = [
  {
    id: 1,
    name: 'LeBron James',
    team: 'LA Lakers',
    position: 'SF',
    jerseyNumber: 23,
    photo: 'https://cdn.nba.com/headshots/nba/latest/1040x760/2544.png',
    stats: {
      gamesPlayed: 72,
      pointsPerGame: 27.4,
      assistsPerGame: 8.3,
      reboundsPerGame: 7.1,
      foulsPerGame: 2.1,
      totalShots: 1180,
      fieldGoalPercentage: 51.2,
      threePointPercentage: 41.0,
      freeThrowPercentage: 73.9,
      blocksPerGame: 0.8,
      stealsPerGame: 1.3,
      efgPercentage: 57.2,
    },
    shots: generateShots(120, 51.2),
  },
  {
    id: 2,
    name: 'Stephen Curry',
    team: 'Golden State Warriors',
    position: 'PG',
    jerseyNumber: 30,
    photo: 'https://cdn.nba.com/headshots/nba/latest/1040x760/201939.png',
    stats: {
      gamesPlayed: 68,
      pointsPerGame: 29.6,
      assistsPerGame: 6.3,
      reboundsPerGame: 5.2,
      foulsPerGame: 1.8,
      totalShots: 1345,
      fieldGoalPercentage: 48.7,
      threePointPercentage: 42.7,
      freeThrowPercentage: 91.5,
      blocksPerGame: 0.4,
      stealsPerGame: 1.4,
      efgPercentage: 58.4,
    },
    shots: generateShots(140, 48.7),
  },
  {
    id: 3,
    name: 'Kevin Durant',
    team: 'Phoenix Suns',
    position: 'SF',
    jerseyNumber: 35,
    photo: 'https://cdn.nba.com/headshots/nba/latest/1040x760/201142.png',
    stats: {
      gamesPlayed: 60,
      pointsPerGame: 28.3,
      assistsPerGame: 5.4,
      reboundsPerGame: 6.7,
      foulsPerGame: 2.4,
      totalShots: 1020,
      fieldGoalPercentage: 53.1,
      threePointPercentage: 40.2,
      freeThrowPercentage: 88.1,
      blocksPerGame: 1.1,
      stealsPerGame: 0.9,
      efgPercentage: 59.1,
    },
    shots: generateShots(110, 53.1),
  },
  {
    id: 4,
    name: 'Giannis Antetokounmpo',
    team: 'Milwaukee Bucks',
    position: 'PF',
    jerseyNumber: 34,
    photo: 'https://cdn.nba.com/headshots/nba/latest/1040x760/203507.png',
    stats: {
      gamesPlayed: 70,
      pointsPerGame: 31.1,
      assistsPerGame: 5.8,
      reboundsPerGame: 11.8,
      foulsPerGame: 3.1,
      totalShots: 1290,
      fieldGoalPercentage: 55.3,
      threePointPercentage: 27.5,
      freeThrowPercentage: 64.5,
      blocksPerGame: 1.4,
      stealsPerGame: 1.2,
      efgPercentage: 57.6,
    },
    shots: generateShots(130, 55.3),
  },
  {
    id: 5,
    name: 'Luka Doncic',
    team: 'Dallas Mavericks',
    position: 'PG',
    jerseyNumber: 77,
    photo: 'https://cdn.nba.com/headshots/nba/latest/1040x760/1629029.png',
    stats: {
      gamesPlayed: 66,
      pointsPerGame: 33.9,
      assistsPerGame: 9.8,
      reboundsPerGame: 9.2,
      foulsPerGame: 2.9,
      totalShots: 1410,
      fieldGoalPercentage: 48.7,
      threePointPercentage: 38.0,
      freeThrowPercentage: 78.6,
      blocksPerGame: 0.5,
      stealsPerGame: 1.4,
      efgPercentage: 54.3,
    },
    shots: generateShots(150, 48.7),
  },
];
